#!/bin/sh
set -e
cd "$(dirname "$0")"
rm -rf asm-output
mkdir -p asm-output
cd asm-output
cargo asm >/dev/null
while read t; do
	echo $t
	mkdir -p "$t"
	while read f; do
		n="${f#floatconv::}"
		if [ "$n" != "$f" ]; then
			echo "$t / $n"
			cargo asm --no-color --target=$t "$f" > "$t/$n"
			sed -i '/^_Z.*:$/Q' "$t/$n"
		fi
	done <<<"$(cargo asm --target=$t)"
done <../test-targets
