#!/bin/sh
set -e
cd "$(dirname "$0")"
rm -rf asm-output
mkdir -p asm-output
cd asm-output
fs=$(cargo asm)
while read t; do
	mkdir -p "$t"
	while read f; do
		n="${f#floatconv::}"
		if [ "$n" != "$f" ]; then
			echo "$t / $n"
			cargo asm --no-color --target=$t "$f" > "$t/$n"
		fi
	done <<<"$fs"
done <<EOF
	x86_64-unknown-linux-gnu
	aarch64-unknown-linux-gnu
	i686-unknown-linux-gnu
EOF
